name: CI

on:
  push:
    branches:
      - master

  pull_request:

env:
  RUSTFLAGS: -D warnings

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        run: rustup toolchain install stable --profile minimal --component rustfmt clippy --no-self-update

      - name: Run rustfmt
        run: cargo fmt --check

      - name: Run Clippy
        run: cargo clippy --no-deps -- -D warnings
